// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package repo

import (
	"context"
)

// iteratorForBatchInsertArtifacts implements pgx.CopyFromSource.
type iteratorForBatchInsertArtifacts struct {
	rows                 []BatchInsertArtifactsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertArtifacts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertArtifacts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Icon,
		r.rows[0].StatID,
	}, nil
}

func (r iteratorForBatchInsertArtifacts) Err() error {
	return nil
}

func (q *Queries) BatchInsertArtifacts(ctx context.Context, arg []BatchInsertArtifactsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"artifacts"}, []string{"id", "name", "icon", "stat_id"}, &iteratorForBatchInsertArtifacts{rows: arg})
}

// iteratorForBatchInsertClasses implements pgx.CopyFromSource.
type iteratorForBatchInsertClasses struct {
	rows                 []BatchInsertClassesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertClasses) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertClasses) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Icon,
	}, nil
}

func (r iteratorForBatchInsertClasses) Err() error {
	return nil
}

// Batch insert queries using COPY protocol for efficient seeding
func (q *Queries) BatchInsertClasses(ctx context.Context, arg []BatchInsertClassesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"classes"}, []string{"id", "name", "icon"}, &iteratorForBatchInsertClasses{rows: arg})
}

// iteratorForBatchInsertCreatures implements pgx.CopyFromSource.
type iteratorForBatchInsertCreatures struct {
	rows                 []BatchInsertCreaturesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertCreatures) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertCreatures) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Icon,
		r.rows[0].TraitID,
		r.rows[0].ClassID,
		r.rows[0].RaceID,
	}, nil
}

func (r iteratorForBatchInsertCreatures) Err() error {
	return nil
}

func (q *Queries) BatchInsertCreatures(ctx context.Context, arg []BatchInsertCreaturesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"creatures"}, []string{"id", "name", "icon", "trait_id", "class_id", "race_id"}, &iteratorForBatchInsertCreatures{rows: arg})
}

// iteratorForBatchInsertMaterialStats implements pgx.CopyFromSource.
type iteratorForBatchInsertMaterialStats struct {
	rows                 []BatchInsertMaterialStatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertMaterialStats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertMaterialStats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].MaterialID,
		r.rows[0].StatID,
		r.rows[0].StatId2,
	}, nil
}

func (r iteratorForBatchInsertMaterialStats) Err() error {
	return nil
}

func (q *Queries) BatchInsertMaterialStats(ctx context.Context, arg []BatchInsertMaterialStatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"material_stats"}, []string{"id", "material_id", "stat_id", "stat_id2"}, &iteratorForBatchInsertMaterialStats{rows: arg})
}

// iteratorForBatchInsertMaterials implements pgx.CopyFromSource.
type iteratorForBatchInsertMaterials struct {
	rows                 []BatchInsertMaterialsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertMaterials) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertMaterials) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Icon,
		r.rows[0].Type,
	}, nil
}

func (r iteratorForBatchInsertMaterials) Err() error {
	return nil
}

func (q *Queries) BatchInsertMaterials(ctx context.Context, arg []BatchInsertMaterialsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"materials"}, []string{"id", "name", "icon", "type"}, &iteratorForBatchInsertMaterials{rows: arg})
}

// iteratorForBatchInsertPerks implements pgx.CopyFromSource.
type iteratorForBatchInsertPerks struct {
	rows                 []BatchInsertPerksParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertPerks) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertPerks) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].Icon,
		r.rows[0].SpecializationID,
	}, nil
}

func (r iteratorForBatchInsertPerks) Err() error {
	return nil
}

func (q *Queries) BatchInsertPerks(ctx context.Context, arg []BatchInsertPerksParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"perks"}, []string{"id", "name", "description", "icon", "specialization_id"}, &iteratorForBatchInsertPerks{rows: arg})
}

// iteratorForBatchInsertRaces implements pgx.CopyFromSource.
type iteratorForBatchInsertRaces struct {
	rows                 []BatchInsertRacesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertRaces) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertRaces) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Icon,
	}, nil
}

func (r iteratorForBatchInsertRaces) Err() error {
	return nil
}

func (q *Queries) BatchInsertRaces(ctx context.Context, arg []BatchInsertRacesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"races"}, []string{"id", "name", "icon"}, &iteratorForBatchInsertRaces{rows: arg})
}

// iteratorForBatchInsertRelics implements pgx.CopyFromSource.
type iteratorForBatchInsertRelics struct {
	rows                 []BatchInsertRelicsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertRelics) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertRelics) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Icon,
		r.rows[0].Bonuses,
		r.rows[0].StatID,
	}, nil
}

func (r iteratorForBatchInsertRelics) Err() error {
	return nil
}

func (q *Queries) BatchInsertRelics(ctx context.Context, arg []BatchInsertRelicsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"relics"}, []string{"id", "name", "icon", "bonuses", "stat_id"}, &iteratorForBatchInsertRelics{rows: arg})
}

// iteratorForBatchInsertSpecializations implements pgx.CopyFromSource.
type iteratorForBatchInsertSpecializations struct {
	rows                 []BatchInsertSpecializationsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertSpecializations) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertSpecializations) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].Icon,
	}, nil
}

func (r iteratorForBatchInsertSpecializations) Err() error {
	return nil
}

func (q *Queries) BatchInsertSpecializations(ctx context.Context, arg []BatchInsertSpecializationsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"specializations"}, []string{"id", "name", "description", "icon"}, &iteratorForBatchInsertSpecializations{rows: arg})
}

// iteratorForBatchInsertSpellProperties implements pgx.CopyFromSource.
type iteratorForBatchInsertSpellProperties struct {
	rows                 []BatchInsertSpellPropertiesParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertSpellProperties) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertSpellProperties) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].MaterialID,
	}, nil
}

func (r iteratorForBatchInsertSpellProperties) Err() error {
	return nil
}

func (q *Queries) BatchInsertSpellProperties(ctx context.Context, arg []BatchInsertSpellPropertiesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"spell_properties"}, []string{"id", "name", "material_id"}, &iteratorForBatchInsertSpellProperties{rows: arg})
}

// iteratorForBatchInsertSpells implements pgx.CopyFromSource.
type iteratorForBatchInsertSpells struct {
	rows                 []BatchInsertSpellsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertSpells) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertSpells) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].Charges,
		r.rows[0].ClassID,
	}, nil
}

func (r iteratorForBatchInsertSpells) Err() error {
	return nil
}

func (q *Queries) BatchInsertSpells(ctx context.Context, arg []BatchInsertSpellsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"spells"}, []string{"id", "name", "description", "charges", "class_id"}, &iteratorForBatchInsertSpells{rows: arg})
}

// iteratorForBatchInsertStats implements pgx.CopyFromSource.
type iteratorForBatchInsertStats struct {
	rows                 []BatchInsertStatsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertStats) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertStats) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Type,
		r.rows[0].Icon,
	}, nil
}

func (r iteratorForBatchInsertStats) Err() error {
	return nil
}

func (q *Queries) BatchInsertStats(ctx context.Context, arg []BatchInsertStatsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"stats"}, []string{"id", "type", "icon"}, &iteratorForBatchInsertStats{rows: arg})
}

// iteratorForBatchInsertTraits implements pgx.CopyFromSource.
type iteratorForBatchInsertTraits struct {
	rows                 []BatchInsertTraitsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertTraits) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertTraits) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].MaterialID,
	}, nil
}

func (r iteratorForBatchInsertTraits) Err() error {
	return nil
}

func (q *Queries) BatchInsertTraits(ctx context.Context, arg []BatchInsertTraitsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"traits"}, []string{"id", "name", "description", "material_id"}, &iteratorForBatchInsertTraits{rows: arg})
}
