// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MaterialType string

const (
	MaterialTypeStat  MaterialType = "stat"
	MaterialTypeTrick MaterialType = "trick"
	MaterialTypeTrait MaterialType = "trait"
)

func (e *MaterialType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaterialType(s)
	case string:
		*e = MaterialType(s)
	default:
		return fmt.Errorf("unsupported scan type for MaterialType: %T", src)
	}
	return nil
}

type NullMaterialType struct {
	MaterialType MaterialType `json:"material_type"`
	Valid        bool         `json:"valid"` // Valid is true if MaterialType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaterialType) Scan(value interface{}) error {
	if value == nil {
		ns.MaterialType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaterialType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaterialType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaterialType), nil
}

type StatType string

const (
	StatTypeHealth       StatType = "health"
	StatTypeAttack       StatType = "attack"
	StatTypeIntelligence StatType = "intelligence"
	StatTypeDefense      StatType = "defense"
	StatTypeSpeed        StatType = "speed"
)

func (e *StatType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatType(s)
	case string:
		*e = StatType(s)
	default:
		return fmt.Errorf("unsupported scan type for StatType: %T", src)
	}
	return nil
}

type NullStatType struct {
	StatType StatType `json:"stat_type"`
	Valid    bool     `json:"valid"` // Valid is true if StatType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatType) Scan(value interface{}) error {
	if value == nil {
		ns.StatType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatType), nil
}

type Artifact struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Icon   []byte `json:"icon"`
	StatID int32  `json:"stat_id"`
}

type Class struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Icon []byte `json:"icon"`
}

type Creature struct {
	ID      int32       `json:"id"`
	Name    string      `json:"name"`
	Icon    []byte      `json:"icon"`
	TraitID pgtype.Int4 `json:"trait_id"`
	ClassID int32       `json:"class_id"`
	RaceID  int32       `json:"race_id"`
}

type CreatureStatGrowth struct {
	ID         int32 `json:"id"`
	CreatureID int32 `json:"creature_id"`
	StatID     int32 `json:"stat_id"`
	GrowthRate int32 `json:"growth_rate"`
}

type CreaturesView struct {
	ID               int32           `json:"id"`
	Name             string          `json:"name"`
	Icon             interface{}     `json:"icon"`
	Trait            pgtype.Text     `json:"trait"`
	TraitDescription pgtype.Text     `json:"trait_description"`
	Class            string          `json:"class"`
	Race             string          `json:"race"`
	Stats            json.RawMessage `json:"stats"`
}

type Material struct {
	ID   int32        `json:"id"`
	Name string       `json:"name"`
	Icon []byte       `json:"icon"`
	Type MaterialType `json:"type"`
}

type MaterialStat struct {
	ID         int32       `json:"id"`
	MaterialID int32       `json:"material_id"`
	StatID     int32       `json:"stat_id"`
	StatId2    pgtype.Int4 `json:"stat_id2"`
}

type MaterialsView struct {
	ID      int32        `json:"id"`
	Name    string       `json:"name"`
	Icon    interface{}  `json:"icon"`
	Type    MaterialType `json:"type"`
	StatId1 pgtype.Int4  `json:"stat_id1"`
	StatId2 pgtype.Int4  `json:"stat_id2"`
}

type Perk struct {
	ID               int32  `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Icon             []byte `json:"icon"`
	SpecializationID int32  `json:"specialization_id"`
}

type Race struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Icon []byte `json:"icon"`
}

type RacesView struct {
	ID   int32       `json:"id"`
	Name string      `json:"name"`
	Icon interface{} `json:"icon"`
}

type Relic struct {
	ID      int32    `json:"id"`
	Name    string   `json:"name"`
	Icon    []byte   `json:"icon"`
	Bonuses []string `json:"bonuses"`
	StatID  int32    `json:"stat_id"`
}

type RelicsView struct {
	ID       int32        `json:"id"`
	Name     string       `json:"name"`
	Icon     interface{}  `json:"icon"`
	Bonuses  []string     `json:"bonuses"`
	StatID   pgtype.Int4  `json:"stat_id"`
	StatType NullStatType `json:"stat_type"`
}

type Specialization struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        []byte `json:"icon"`
}

type Spell struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Charges     int32  `json:"charges"`
	ClassID     int32  `json:"class_id"`
}

type SpellProperty struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	MaterialID int32  `json:"material_id"`
}

type Stat struct {
	ID   int32    `json:"id"`
	Type StatType `json:"type"`
	Icon []byte   `json:"icon"`
}

type Trait struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	MaterialID  pgtype.Int4 `json:"material_id"`
}
