// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"
)

type MaterialType string

const (
	MaterialTypeStat  MaterialType = "stat"
	MaterialTypeTrick MaterialType = "trick"
	MaterialTypeTrait MaterialType = "trait"
)

func (e *MaterialType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaterialType(s)
	case string:
		*e = MaterialType(s)
	default:
		return fmt.Errorf("unsupported scan type for MaterialType: %T", src)
	}
	return nil
}

type NullMaterialType struct {
	MaterialType MaterialType `json:"material_type"`
	Valid        bool         `json:"valid"` // Valid is true if MaterialType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaterialType) Scan(value interface{}) error {
	if value == nil {
		ns.MaterialType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaterialType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaterialType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaterialType), nil
}

type StatType string

const (
	StatTypeHealth       StatType = "health"
	StatTypeAttack       StatType = "attack"
	StatTypeIntelligence StatType = "intelligence"
	StatTypeDefense      StatType = "defense"
	StatTypeSpeed        StatType = "speed"
)

func (e *StatType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatType(s)
	case string:
		*e = StatType(s)
	default:
		return fmt.Errorf("unsupported scan type for StatType: %T", src)
	}
	return nil
}

type NullStatType struct {
	StatType StatType `json:"stat_type"`
	Valid    bool     `json:"valid"` // Valid is true if StatType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatType) Scan(value interface{}) error {
	if value == nil {
		ns.StatType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatType), nil
}

type Artifact struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        []byte `json:"icon"`
}

type Class struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Icon []byte `json:"icon"`
}

type Creature struct {
	ID      int32  `json:"id"`
	Name    string `json:"name"`
	Image   []byte `json:"image"`
	TraitID int32  `json:"trait_id"`
	ClassID int32  `json:"class_id"`
	RaceID  int32  `json:"race_id"`
}

type Material struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Description string           `json:"description"`
	Icon        []byte           `json:"icon"`
	Type        NullMaterialType `json:"type"`
}

type MaterialStat struct {
	ID         int32 `json:"id"`
	MaterialID int32 `json:"material_id"`
	StatID     int32 `json:"stat_id"`
}

type Perk struct {
	ID               int32  `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Icon             []byte `json:"icon"`
	SpecializationID int32  `json:"specialization_id"`
}

type Race struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Icon []byte `json:"icon"`
}

type Specialization struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Spell struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        []byte `json:"icon"`
	Charges     int32  `json:"charges"`
	ClassID     int32  `json:"class_id"`
}

type SpellProperty struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	MaterialID  int32  `json:"material_id"`
}

type Stat struct {
	ID   int32    `json:"id"`
	Type StatType `json:"type"`
}

type Trait struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	MaterialID  int32  `json:"material_id"`
}
