// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO artifacts (id, name, icon, type)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateArtifactParams struct {
	ID   int32    `json:"id"`
	Name string   `json:"name"`
	Icon []byte   `json:"icon"`
	Type StatType `json:"type"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (int32, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Type,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createClass = `-- name: CreateClass :one
INSERT INTO classes (id, name, icon)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateClassParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Icon []byte `json:"icon"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (int32, error) {
	row := q.db.QueryRow(ctx, createClass, arg.ID, arg.Name, arg.Icon)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createCreature = `-- name: CreateCreature :one
INSERT INTO creatures (id, name, image, trait_id, class_id, race_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateCreatureParams struct {
	ID      int32       `json:"id"`
	Name    string      `json:"name"`
	Image   []byte      `json:"image"`
	TraitID pgtype.Int4 `json:"trait_id"`
	ClassID int32       `json:"class_id"`
	RaceID  int32       `json:"race_id"`
}

func (q *Queries) CreateCreature(ctx context.Context, arg CreateCreatureParams) (int32, error) {
	row := q.db.QueryRow(ctx, createCreature,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.TraitID,
		arg.ClassID,
		arg.RaceID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (id, name, icon, type)
VALUES ($1, $2, $3, $4)
RETURNING id,
    name,
    icon,
    type
`

type CreateMaterialParams struct {
	ID   int32            `json:"id"`
	Name string           `json:"name"`
	Icon []byte           `json:"icon"`
	Type NullMaterialType `json:"type"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Type,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Type,
	)
	return i, err
}

const createMaterialStat = `-- name: CreateMaterialStat :one
INSERT INTO material_stats (material_id, stat_id, stat_id2, id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateMaterialStatParams struct {
	MaterialID int32       `json:"material_id"`
	StatID     int32       `json:"stat_id"`
	StatId2    pgtype.Int4 `json:"stat_id2"`
	ID         int32       `json:"id"`
}

func (q *Queries) CreateMaterialStat(ctx context.Context, arg CreateMaterialStatParams) (int32, error) {
	row := q.db.QueryRow(ctx, createMaterialStat,
		arg.MaterialID,
		arg.StatID,
		arg.StatId2,
		arg.ID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createPerk = `-- name: CreatePerk :one
INSERT INTO perks (id, name, description, icon, specialization_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreatePerkParams struct {
	ID               int32  `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Icon             []byte `json:"icon"`
	SpecializationID int32  `json:"specialization_id"`
}

func (q *Queries) CreatePerk(ctx context.Context, arg CreatePerkParams) (int32, error) {
	row := q.db.QueryRow(ctx, createPerk,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.SpecializationID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createRace = `-- name: CreateRace :one
INSERT INTO races (id, name, icon)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateRaceParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Icon []byte `json:"icon"`
}

func (q *Queries) CreateRace(ctx context.Context, arg CreateRaceParams) (int32, error) {
	row := q.db.QueryRow(ctx, createRace, arg.ID, arg.Name, arg.Icon)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createSpecialization = `-- name: CreateSpecialization :one
INSERT INTO specializations (id, name, description)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateSpecializationParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateSpecialization(ctx context.Context, arg CreateSpecializationParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSpecialization, arg.ID, arg.Name, arg.Description)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createSpell = `-- name: CreateSpell :one
INSERT INTO spells (id, name, description, icon, charges, class_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateSpellParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        []byte `json:"icon"`
	Charges     int32  `json:"charges"`
	ClassID     int32  `json:"class_id"`
}

func (q *Queries) CreateSpell(ctx context.Context, arg CreateSpellParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSpell,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Charges,
		arg.ClassID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createSpellProperty = `-- name: CreateSpellProperty :one
INSERT INTO spell_properties (id, name, material_id)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateSpellPropertyParams struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	MaterialID int32  `json:"material_id"`
}

func (q *Queries) CreateSpellProperty(ctx context.Context, arg CreateSpellPropertyParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSpellProperty, arg.ID, arg.Name, arg.MaterialID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createStat = `-- name: CreateStat :one
INSERT INTO stats (id, type)
VALUES ($1, $2)
RETURNING id
`

type CreateStatParams struct {
	ID   int32    `json:"id"`
	Type StatType `json:"type"`
}

func (q *Queries) CreateStat(ctx context.Context, arg CreateStatParams) (int32, error) {
	row := q.db.QueryRow(ctx, createStat, arg.ID, arg.Type)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createTrait = `-- name: CreateTrait :one
INSERT INTO traits (id, name, description, material_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateTraitParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	MaterialID  pgtype.Int4 `json:"material_id"`
}

func (q *Queries) CreateTrait(ctx context.Context, arg CreateTraitParams) (int32, error) {
	row := q.db.QueryRow(ctx, createTrait,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.MaterialID,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifacts
WHERE id = $1
`

func (q *Queries) DeleteArtifact(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteArtifact, id)
	return err
}

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM classes
WHERE id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteClass, id)
	return err
}

const deleteCreature = `-- name: DeleteCreature :exec
DELETE FROM creatures
WHERE id = $1
`

func (q *Queries) DeleteCreature(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCreature, id)
	return err
}

const deleteMaterial = `-- name: DeleteMaterial :exec
DELETE FROM materials
WHERE id = $1
`

func (q *Queries) DeleteMaterial(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMaterial, id)
	return err
}

const deleteMaterialStat = `-- name: DeleteMaterialStat :exec
DELETE FROM material_stats
WHERE id = $1
`

func (q *Queries) DeleteMaterialStat(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMaterialStat, id)
	return err
}

const deletePerk = `-- name: DeletePerk :exec
DELETE FROM perks
WHERE id = $1
`

func (q *Queries) DeletePerk(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePerk, id)
	return err
}

const deleteRace = `-- name: DeleteRace :exec
DELETE FROM races
WHERE id = $1
`

func (q *Queries) DeleteRace(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRace, id)
	return err
}

const deleteSpecialization = `-- name: DeleteSpecialization :exec
DELETE FROM specializations
WHERE id = $1
`

func (q *Queries) DeleteSpecialization(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSpecialization, id)
	return err
}

const deleteSpell = `-- name: DeleteSpell :exec
DELETE FROM spells
WHERE id = $1
`

func (q *Queries) DeleteSpell(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSpell, id)
	return err
}

const deleteSpellProperty = `-- name: DeleteSpellProperty :exec
DELETE FROM spell_properties
WHERE id = $1
`

func (q *Queries) DeleteSpellProperty(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSpellProperty, id)
	return err
}

const deleteStat = `-- name: DeleteStat :exec
DELETE FROM stats
WHERE id = $1
`

func (q *Queries) DeleteStat(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteStat, id)
	return err
}

const deleteTrait = `-- name: DeleteTrait :exec
DELETE FROM traits
WHERE id = $1
`

func (q *Queries) DeleteTrait(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTrait, id)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, name, icon, type
FROM artifacts
WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id int32) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Type,
	)
	return i, err
}

const getArtifacts = `-- name: GetArtifacts :many
SELECT id, name, icon, type
FROM artifacts
`

func (q *Queries) GetArtifacts(ctx context.Context) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, getArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByName = `-- name: GetArtifactsByName :many
SELECT id, name, icon, type
FROM artifacts
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetArtifactsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, getArtifactsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClass = `-- name: GetClass :one
SELECT id, name, icon
FROM classes
WHERE id = $1
`

func (q *Queries) GetClass(ctx context.Context, id int32) (Class, error) {
	row := q.db.QueryRow(ctx, getClass, id)
	var i Class
	err := row.Scan(&i.ID, &i.Name, &i.Icon)
	return i, err
}

const getClasses = `-- name: GetClasses :many
SELECT id, name, icon
FROM classes
`

func (q *Queries) GetClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.Query(ctx, getClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassesByName = `-- name: GetClassesByName :many
SELECT id, name, icon
FROM classes
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetClassesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Class, error) {
	rows, err := q.db.Query(ctx, getClassesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreature = `-- name: GetCreature :one
SELECT id, name, image, trait_id, class_id, race_id
FROM creatures
WHERE id = $1
`

func (q *Queries) GetCreature(ctx context.Context, id int32) (Creature, error) {
	row := q.db.QueryRow(ctx, getCreature, id)
	var i Creature
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.TraitID,
		&i.ClassID,
		&i.RaceID,
	)
	return i, err
}

const getCreatures = `-- name: GetCreatures :many
SELECT id, name, image, trait_id, class_id, race_id
FROM creatures
`

func (q *Queries) GetCreatures(ctx context.Context) ([]Creature, error) {
	rows, err := q.db.Query(ctx, getCreatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creature
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.TraitID,
			&i.ClassID,
			&i.RaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByClassName = `-- name: GetCreaturesByClassName :many
SELECT c.id, c.name, c.image, c.trait_id, c.class_id, c.race_id
FROM creatures c
    JOIN classes cl ON c.class_id = cl.id
WHERE cl.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByClassName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error) {
	rows, err := q.db.Query(ctx, getCreaturesByClassName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creature
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.TraitID,
			&i.ClassID,
			&i.RaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByName = `-- name: GetCreaturesByName :many
SELECT id, name, image, trait_id, class_id, race_id
FROM creatures
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error) {
	rows, err := q.db.Query(ctx, getCreaturesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creature
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.TraitID,
			&i.ClassID,
			&i.RaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByRaceName = `-- name: GetCreaturesByRaceName :many
SELECT c.id, c.name, c.image, c.trait_id, c.class_id, c.race_id
FROM creatures c
    JOIN races r ON c.race_id = r.id
WHERE r.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByRaceName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error) {
	rows, err := q.db.Query(ctx, getCreaturesByRaceName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creature
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.TraitID,
			&i.ClassID,
			&i.RaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByTraitName = `-- name: GetCreaturesByTraitName :many
SELECT c.id, c.name, c.image, c.trait_id, c.class_id, c.race_id
FROM creatures c
    JOIN traits t ON c.trait_id = t.id
WHERE t.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByTraitName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error) {
	rows, err := q.db.Query(ctx, getCreaturesByTraitName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creature
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.TraitID,
			&i.ClassID,
			&i.RaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterial = `-- name: GetMaterial :one
SELECT m.id,
    m.name,
    m.icon,
    m.type,
    ms.id as stat_id,
    ms.stat_id
FROM materials m
    LEFT JOIN material_stats ms ON m.id = ms.material_id
WHERE m.id = $1
`

type GetMaterialRow struct {
	ID       int32            `json:"id"`
	Name     string           `json:"name"`
	Icon     []byte           `json:"icon"`
	Type     NullMaterialType `json:"type"`
	StatID   pgtype.Int4      `json:"stat_id"`
	StatID_2 pgtype.Int4      `json:"stat_id_2"`
}

func (q *Queries) GetMaterial(ctx context.Context, id int32) (GetMaterialRow, error) {
	row := q.db.QueryRow(ctx, getMaterial, id)
	var i GetMaterialRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Type,
		&i.StatID,
		&i.StatID_2,
	)
	return i, err
}

const getMaterialStats = `-- name: GetMaterialStats :many
SELECT id,
    material_id,
    stat_id
FROM material_stats
WHERE material_id = $1
`

type GetMaterialStatsRow struct {
	ID         int32 `json:"id"`
	MaterialID int32 `json:"material_id"`
	StatID     int32 `json:"stat_id"`
}

func (q *Queries) GetMaterialStats(ctx context.Context, materialID int32) ([]GetMaterialStatsRow, error) {
	rows, err := q.db.Query(ctx, getMaterialStats, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaterialStatsRow
	for rows.Next() {
		var i GetMaterialStatsRow
		if err := rows.Scan(&i.ID, &i.MaterialID, &i.StatID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterials = `-- name: GetMaterials :many
SELECT m.id,
    m.name,
    m.icon,
    m.type,
    ms.id as stat_id,
    ms.stat_id
FROM materials m
    LEFT JOIN material_stats ms ON m.id = ms.material_id
`

type GetMaterialsRow struct {
	ID       int32            `json:"id"`
	Name     string           `json:"name"`
	Icon     []byte           `json:"icon"`
	Type     NullMaterialType `json:"type"`
	StatID   pgtype.Int4      `json:"stat_id"`
	StatID_2 pgtype.Int4      `json:"stat_id_2"`
}

func (q *Queries) GetMaterials(ctx context.Context) ([]GetMaterialsRow, error) {
	rows, err := q.db.Query(ctx, getMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaterialsRow
	for rows.Next() {
		var i GetMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Type,
			&i.StatID,
			&i.StatID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialsByName = `-- name: GetMaterialsByName :many
SELECT m.id,
    m.name,
    m.icon,
    m.type,
    ms.id as stat_id,
    ms.stat_id
FROM materials m
    LEFT JOIN material_stats ms ON m.id = ms.material_id
WHERE m.name ILIKE '%' || $1 || '%'
`

type GetMaterialsByNameRow struct {
	ID       int32            `json:"id"`
	Name     string           `json:"name"`
	Icon     []byte           `json:"icon"`
	Type     NullMaterialType `json:"type"`
	StatID   pgtype.Int4      `json:"stat_id"`
	StatID_2 pgtype.Int4      `json:"stat_id_2"`
}

func (q *Queries) GetMaterialsByName(ctx context.Context, dollar_1 pgtype.Text) ([]GetMaterialsByNameRow, error) {
	rows, err := q.db.Query(ctx, getMaterialsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaterialsByNameRow
	for rows.Next() {
		var i GetMaterialsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Type,
			&i.StatID,
			&i.StatID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerk = `-- name: GetPerk :one
SELECT id, name, description, icon, specialization_id
FROM perks
WHERE id = $1
`

func (q *Queries) GetPerk(ctx context.Context, id int32) (Perk, error) {
	row := q.db.QueryRow(ctx, getPerk, id)
	var i Perk
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.SpecializationID,
	)
	return i, err
}

const getPerks = `-- name: GetPerks :many
SELECT id, name, description, icon, specialization_id
FROM perks
`

func (q *Queries) GetPerks(ctx context.Context) ([]Perk, error) {
	rows, err := q.db.Query(ctx, getPerks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Perk
	for rows.Next() {
		var i Perk
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.SpecializationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerksByName = `-- name: GetPerksByName :many
SELECT id, name, description, icon, specialization_id
FROM perks
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetPerksByName(ctx context.Context, dollar_1 pgtype.Text) ([]Perk, error) {
	rows, err := q.db.Query(ctx, getPerksByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Perk
	for rows.Next() {
		var i Perk
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.SpecializationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRace = `-- name: GetRace :one
SELECT id, name, icon
FROM races
WHERE id = $1
`

func (q *Queries) GetRace(ctx context.Context, id int32) (Race, error) {
	row := q.db.QueryRow(ctx, getRace, id)
	var i Race
	err := row.Scan(&i.ID, &i.Name, &i.Icon)
	return i, err
}

const getRaces = `-- name: GetRaces :many
SELECT id, name, icon
FROM races
`

func (q *Queries) GetRaces(ctx context.Context) ([]Race, error) {
	rows, err := q.db.Query(ctx, getRaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Race
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByClassName = `-- name: GetRacesByClassName :many
SELECT r.id, r.name, r.icon
FROM races r
    JOIN creatures c ON r.id = c.race
    JOIN classes cl ON c.class_id = cl.id
WHERE cl.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByClassName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error) {
	rows, err := q.db.Query(ctx, getRacesByClassName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Race
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByCreatureName = `-- name: GetRacesByCreatureName :many
SELECT r.id, r.name, r.icon
FROM races r
    JOIN creatures c ON r.id = c.race_id
WHERE c.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByCreatureName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error) {
	rows, err := q.db.Query(ctx, getRacesByCreatureName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Race
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByName = `-- name: GetRacesByName :many
SELECT id, name, icon
FROM races
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error) {
	rows, err := q.db.Query(ctx, getRacesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Race
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByTraitName = `-- name: GetRacesByTraitName :many
SELECT r.id, r.name, r.icon
FROM races r
    JOIN creatures c ON r.id = c.race_id
    JOIN traits t ON c.trait_id = t.id
WHERE t.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByTraitName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error) {
	rows, err := q.db.Query(ctx, getRacesByTraitName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Race
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecialization = `-- name: GetSpecialization :one
SELECT id, name, description, icon
FROM specializations
WHERE id = $1
`

func (q *Queries) GetSpecialization(ctx context.Context, id int32) (Specialization, error) {
	row := q.db.QueryRow(ctx, getSpecialization, id)
	var i Specialization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
	)
	return i, err
}

const getSpecializations = `-- name: GetSpecializations :many
SELECT id, name, description, icon
FROM specializations
`

func (q *Queries) GetSpecializations(ctx context.Context) ([]Specialization, error) {
	rows, err := q.db.Query(ctx, getSpecializations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialization
	for rows.Next() {
		var i Specialization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecializationsByName = `-- name: GetSpecializationsByName :many
SELECT id, name, description, icon
FROM specializations
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetSpecializationsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Specialization, error) {
	rows, err := q.db.Query(ctx, getSpecializationsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialization
	for rows.Next() {
		var i Specialization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpell = `-- name: GetSpell :one
SELECT id, name, description, icon, charges, class_id
FROM spells
WHERE id = $1
`

func (q *Queries) GetSpell(ctx context.Context, id int32) (Spell, error) {
	row := q.db.QueryRow(ctx, getSpell, id)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Charges,
		&i.ClassID,
	)
	return i, err
}

const getSpellProperties = `-- name: GetSpellProperties :many
SELECT id, name, material_id
FROM spell_properties
`

func (q *Queries) GetSpellProperties(ctx context.Context) ([]SpellProperty, error) {
	rows, err := q.db.Query(ctx, getSpellProperties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellProperty
	for rows.Next() {
		var i SpellProperty
		if err := rows.Scan(&i.ID, &i.Name, &i.MaterialID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellPropertiesByName = `-- name: GetSpellPropertiesByName :many
SELECT id, name, material_id
FROM spell_properties
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetSpellPropertiesByName(ctx context.Context, dollar_1 pgtype.Text) ([]SpellProperty, error) {
	rows, err := q.db.Query(ctx, getSpellPropertiesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellProperty
	for rows.Next() {
		var i SpellProperty
		if err := rows.Scan(&i.ID, &i.Name, &i.MaterialID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellProperty = `-- name: GetSpellProperty :one
SELECT id, name, material_id
FROM spell_properties
WHERE id = $1
`

func (q *Queries) GetSpellProperty(ctx context.Context, id int32) (SpellProperty, error) {
	row := q.db.QueryRow(ctx, getSpellProperty, id)
	var i SpellProperty
	err := row.Scan(&i.ID, &i.Name, &i.MaterialID)
	return i, err
}

const getSpells = `-- name: GetSpells :many
SELECT id, name, description, icon, charges, class_id
FROM spells
`

func (q *Queries) GetSpells(ctx context.Context) ([]Spell, error) {
	rows, err := q.db.Query(ctx, getSpells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Spell
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Charges,
			&i.ClassID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsByName = `-- name: GetSpellsByName :many
SELECT id, name, description, icon, charges, class_id
FROM spells
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetSpellsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Spell, error) {
	rows, err := q.db.Query(ctx, getSpellsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Spell
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Charges,
			&i.ClassID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStat = `-- name: GetStat :one
SELECT id, type
FROM stats
WHERE id = $1
`

func (q *Queries) GetStat(ctx context.Context, id int32) (Stat, error) {
	row := q.db.QueryRow(ctx, getStat, id)
	var i Stat
	err := row.Scan(&i.ID, &i.Type)
	return i, err
}

const getStats = `-- name: GetStats :many
SELECT id, type
FROM stats
`

func (q *Queries) GetStats(ctx context.Context) ([]Stat, error) {
	rows, err := q.db.Query(ctx, getStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stat
	for rows.Next() {
		var i Stat
		if err := rows.Scan(&i.ID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByType = `-- name: GetStatsByType :many
SELECT id, type
FROM stats
WHERE type::text ILIKE '%' || $1 || '%'
`

func (q *Queries) GetStatsByType(ctx context.Context, dollar_1 pgtype.Text) ([]Stat, error) {
	rows, err := q.db.Query(ctx, getStatsByType, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stat
	for rows.Next() {
		var i Stat
		if err := rows.Scan(&i.ID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsCount = `-- name: GetStatsCount :one
SELECT COUNT(*) FROM stats
`

func (q *Queries) GetStatsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getStatsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTrait = `-- name: GetTrait :one
SELECT id, name, description, material_id
FROM traits
WHERE id = $1
`

func (q *Queries) GetTrait(ctx context.Context, id int32) (Trait, error) {
	row := q.db.QueryRow(ctx, getTrait, id)
	var i Trait
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MaterialID,
	)
	return i, err
}

const getTraits = `-- name: GetTraits :many
SELECT id, name, description, material_id
FROM traits
`

func (q *Queries) GetTraits(ctx context.Context) ([]Trait, error) {
	rows, err := q.db.Query(ctx, getTraits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trait
	for rows.Next() {
		var i Trait
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraitsByCreatureName = `-- name: GetTraitsByCreatureName :many
SELECT t.id, t.name, t.description, t.material_id
FROM traits t
    JOIN creatures c ON t.id = c.trait_id
WHERE c.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetTraitsByCreatureName(ctx context.Context, dollar_1 pgtype.Text) ([]Trait, error) {
	rows, err := q.db.Query(ctx, getTraitsByCreatureName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trait
	for rows.Next() {
		var i Trait
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraitsByName = `-- name: GetTraitsByName :many
SELECT id, name, description, material_id
FROM traits
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetTraitsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Trait, error) {
	rows, err := q.db.Query(ctx, getTraitsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trait
	for rows.Next() {
		var i Trait
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materialExists = `-- name: MaterialExists :one
SELECT EXISTS(SELECT 1 FROM materials WHERE id = $1) as exists
`

func (q *Queries) MaterialExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, materialExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const traitExists = `-- name: TraitExists :one
SELECT EXISTS(SELECT 1 FROM traits WHERE id = $1) as exists
`

func (q *Queries) TraitExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, traitExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMaterialStat = `-- name: UpdateMaterialStat :exec
UPDATE material_stats
SET id = $3
WHERE material_id = $1
    AND stat_id = $2
`

type UpdateMaterialStatParams struct {
	MaterialID int32 `json:"material_id"`
	StatID     int32 `json:"stat_id"`
	ID         int32 `json:"id"`
}

func (q *Queries) UpdateMaterialStat(ctx context.Context, arg UpdateMaterialStatParams) error {
	_, err := q.db.Exec(ctx, updateMaterialStat, arg.MaterialID, arg.StatID, arg.ID)
	return err
}
