// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertArtifactsParams struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Icon   []byte `json:"icon"`
	StatID int32  `json:"stat_id"`
}

type BatchInsertClassesParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Icon []byte `json:"icon"`
}

type BatchInsertCreatureStatGrowthParams struct {
	ID         int32 `json:"id"`
	CreatureID int32 `json:"creature_id"`
	StatID     int32 `json:"stat_id"`
	GrowthRate int32 `json:"growth_rate"`
}

type BatchInsertCreaturesParams struct {
	ID      int32       `json:"id"`
	Name    string      `json:"name"`
	Icon    []byte      `json:"icon"`
	TraitID pgtype.Int4 `json:"trait_id"`
	ClassID int32       `json:"class_id"`
	RaceID  int32       `json:"race_id"`
}

type BatchInsertMaterialStatsParams struct {
	ID         int32       `json:"id"`
	MaterialID int32       `json:"material_id"`
	StatID     int32       `json:"stat_id"`
	StatId2    pgtype.Int4 `json:"stat_id2"`
}

type BatchInsertMaterialsParams struct {
	ID   int32        `json:"id"`
	Name string       `json:"name"`
	Icon []byte       `json:"icon"`
	Type MaterialType `json:"type"`
}

type BatchInsertPerksParams struct {
	ID               int32  `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Icon             []byte `json:"icon"`
	SpecializationID int32  `json:"specialization_id"`
}

type BatchInsertRacesParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Icon []byte `json:"icon"`
}

type BatchInsertRelicsParams struct {
	ID      int32    `json:"id"`
	Name    string   `json:"name"`
	Icon    []byte   `json:"icon"`
	Bonuses []string `json:"bonuses"`
	StatID  int32    `json:"stat_id"`
}

type BatchInsertSpecializationsParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        []byte `json:"icon"`
}

type BatchInsertSpellPropertiesParams struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	MaterialID int32  `json:"material_id"`
}

type BatchInsertSpellsParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Charges     int32  `json:"charges"`
	ClassID     int32  `json:"class_id"`
}

type BatchInsertStatsParams struct {
	ID   int32    `json:"id"`
	Type StatType `json:"type"`
	Icon []byte   `json:"icon"`
}

type BatchInsertTraitsParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	MaterialID  pgtype.Int4 `json:"material_id"`
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, name, icon, stat_id
FROM artifacts
WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id int32) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.StatID,
	)
	return i, err
}

const getArtifacts = `-- name: GetArtifacts :many
SELECT id, name, icon, stat_id
FROM artifacts
`

func (q *Queries) GetArtifacts(ctx context.Context) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, getArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.StatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByName = `-- name: GetArtifactsByName :many
SELECT id, name, icon, stat_id
FROM artifacts
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetArtifactsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, getArtifactsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.StatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClass = `-- name: GetClass :one
SELECT id, name, icon
FROM classes
WHERE id = $1
`

func (q *Queries) GetClass(ctx context.Context, id int32) (Class, error) {
	row := q.db.QueryRow(ctx, getClass, id)
	var i Class
	err := row.Scan(&i.ID, &i.Name, &i.Icon)
	return i, err
}

const getClasses = `-- name: GetClasses :many
SELECT id, name, icon
FROM classes
`

func (q *Queries) GetClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.Query(ctx, getClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassesByName = `-- name: GetClassesByName :many
SELECT id, name, icon
FROM classes
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetClassesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Class, error) {
	rows, err := q.db.Query(ctx, getClassesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreature = `-- name: GetCreature :one
SELECT
    c.id,
    c.name,
    '/icons/creatures/'|| c.id::text AS icon,
    t.name AS trait,
    t.description AS trait_description,
    cl.name AS class,
    r.name AS race,
    jsonb_object_agg(s.type, csg.growth_rate) AS stats
FROM creatures c
JOIN classes cl
    ON c.class_id = cl.id
JOIN races r
    ON c.race_id = r.id
LEFT JOIN traits t
    ON c.trait_id = t.id
JOIN creature_stat_growth csg
    ON c.id = csg.creature_id
JOIN stats s
    ON csg.stat_id = s.id
WHERE c.id = $1
GROUP BY
    c.id,
    c.name,
    c.icon,
    t.name,
    t.description,
    cl.name,
    r.name
`

type GetCreatureRow struct {
	ID               int32           `json:"id"`
	Name             string          `json:"name"`
	Icon             interface{}     `json:"icon"`
	Trait            pgtype.Text     `json:"trait"`
	TraitDescription pgtype.Text     `json:"trait_description"`
	Class            string          `json:"class"`
	Race             string          `json:"race"`
	Stats            json.RawMessage `json:"stats"`
}

func (q *Queries) GetCreature(ctx context.Context, id int32) (GetCreatureRow, error) {
	row := q.db.QueryRow(ctx, getCreature, id)
	var i GetCreatureRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Trait,
		&i.TraitDescription,
		&i.Class,
		&i.Race,
		&i.Stats,
	)
	return i, err
}

const getCreatureIconById = `-- name: GetCreatureIconById :one
SELECT icon
FROM creatures
WHERE id = $1
`

func (q *Queries) GetCreatureIconById(ctx context.Context, id int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCreatureIconById, id)
	var icon []byte
	err := row.Scan(&icon)
	return icon, err
}

const getCreatures = `-- name: GetCreatures :many
SELECT c.id,
    c.name,
    '/icons/creatures/'|| c.id::text AS icon,
    t.name as trait,
    cl.name as class,
    r.name as race
FROM creatures c
    LEFT JOIN traits t ON c.trait_id = t.id
    LEFT JOIN classes cl ON c.class_id = cl.id
    LEFT JOIN races r ON c.race_id = r.id
`

type GetCreaturesRow struct {
	ID    int32       `json:"id"`
	Name  string      `json:"name"`
	Icon  interface{} `json:"icon"`
	Trait pgtype.Text `json:"trait"`
	Class pgtype.Text `json:"class"`
	Race  pgtype.Text `json:"race"`
}

func (q *Queries) GetCreatures(ctx context.Context) ([]GetCreaturesRow, error) {
	rows, err := q.db.Query(ctx, getCreatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCreaturesRow
	for rows.Next() {
		var i GetCreaturesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Trait,
			&i.Class,
			&i.Race,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByClassName = `-- name: GetCreaturesByClassName :many
SELECT c.id, c.name, c.icon, c.trait_id, c.class_id, c.race_id
FROM creatures c
    JOIN classes cl ON c.class_id = cl.id
WHERE cl.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByClassName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error) {
	rows, err := q.db.Query(ctx, getCreaturesByClassName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creature
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.TraitID,
			&i.ClassID,
			&i.RaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByName = `-- name: GetCreaturesByName :many
SELECT id, name, icon, trait_id, class_id, race_id
FROM creatures
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error) {
	rows, err := q.db.Query(ctx, getCreaturesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creature
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.TraitID,
			&i.ClassID,
			&i.RaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByRaceName = `-- name: GetCreaturesByRaceName :many
SELECT c.id, c.name, c.icon, c.trait_id, c.class_id, c.race_id
FROM creatures c
    JOIN races r ON c.race_id = r.id
WHERE r.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByRaceName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error) {
	rows, err := q.db.Query(ctx, getCreaturesByRaceName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creature
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.TraitID,
			&i.ClassID,
			&i.RaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByTraitName = `-- name: GetCreaturesByTraitName :many
SELECT c.id, c.name, c.icon, c.trait_id, c.class_id, c.race_id
FROM creatures c
    JOIN traits t ON c.trait_id = t.id
WHERE t.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByTraitName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error) {
	rows, err := q.db.Query(ctx, getCreaturesByTraitName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Creature
	for rows.Next() {
		var i Creature
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.TraitID,
			&i.ClassID,
			&i.RaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterial = `-- name: GetMaterial :one
SELECT m.id,
    m.name,
    '/icons/materials/'|| m.id::text AS icon,
    m.type,
    ms.id as stat_id,
    ms.stat_id
FROM materials m
    LEFT JOIN material_stats ms ON m.id = ms.material_id
WHERE m.id = $1
`

type GetMaterialRow struct {
	ID       int32        `json:"id"`
	Name     string       `json:"name"`
	Icon     interface{}  `json:"icon"`
	Type     MaterialType `json:"type"`
	StatID   pgtype.Int4  `json:"stat_id"`
	StatID_2 pgtype.Int4  `json:"stat_id_2"`
}

func (q *Queries) GetMaterial(ctx context.Context, id int32) (GetMaterialRow, error) {
	row := q.db.QueryRow(ctx, getMaterial, id)
	var i GetMaterialRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Type,
		&i.StatID,
		&i.StatID_2,
	)
	return i, err
}

const getMaterialIconById = `-- name: GetMaterialIconById :one
SELECT icon
FROM materials
WHERE id = $1
`

func (q *Queries) GetMaterialIconById(ctx context.Context, id int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, getMaterialIconById, id)
	var icon []byte
	err := row.Scan(&icon)
	return icon, err
}

const getMaterialStats = `-- name: GetMaterialStats :many
SELECT id,
    material_id,
    stat_id
FROM material_stats
WHERE material_id = $1
`

type GetMaterialStatsRow struct {
	ID         int32 `json:"id"`
	MaterialID int32 `json:"material_id"`
	StatID     int32 `json:"stat_id"`
}

func (q *Queries) GetMaterialStats(ctx context.Context, materialID int32) ([]GetMaterialStatsRow, error) {
	rows, err := q.db.Query(ctx, getMaterialStats, materialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaterialStatsRow
	for rows.Next() {
		var i GetMaterialStatsRow
		if err := rows.Scan(&i.ID, &i.MaterialID, &i.StatID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterials = `-- name: GetMaterials :many
SELECT m.id,
    m.name,
    m.icon,
    m.type,
    ms.id as stat_id,
    ms.stat_id
FROM materials m
    LEFT JOIN material_stats ms ON m.id = ms.material_id
`

type GetMaterialsRow struct {
	ID       int32        `json:"id"`
	Name     string       `json:"name"`
	Icon     []byte       `json:"icon"`
	Type     MaterialType `json:"type"`
	StatID   pgtype.Int4  `json:"stat_id"`
	StatID_2 pgtype.Int4  `json:"stat_id_2"`
}

func (q *Queries) GetMaterials(ctx context.Context) ([]GetMaterialsRow, error) {
	rows, err := q.db.Query(ctx, getMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaterialsRow
	for rows.Next() {
		var i GetMaterialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Type,
			&i.StatID,
			&i.StatID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialsByName = `-- name: GetMaterialsByName :many
SELECT m.id,
    m.name,
    '/icons/materials/'|| m.id::text AS icon,
    m.type,
    ms.id as stat_id,
    ms.stat_id
FROM materials m
    LEFT JOIN material_stats ms ON m.id = ms.material_id
WHERE m.name ILIKE '%' || $1 || '%'
`

type GetMaterialsByNameRow struct {
	ID       int32        `json:"id"`
	Name     string       `json:"name"`
	Icon     interface{}  `json:"icon"`
	Type     MaterialType `json:"type"`
	StatID   pgtype.Int4  `json:"stat_id"`
	StatID_2 pgtype.Int4  `json:"stat_id_2"`
}

func (q *Queries) GetMaterialsByName(ctx context.Context, dollar_1 pgtype.Text) ([]GetMaterialsByNameRow, error) {
	rows, err := q.db.Query(ctx, getMaterialsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMaterialsByNameRow
	for rows.Next() {
		var i GetMaterialsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Type,
			&i.StatID,
			&i.StatID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerk = `-- name: GetPerk :one
SELECT id, name, description, icon, specialization_id
FROM perks
WHERE id = $1
`

func (q *Queries) GetPerk(ctx context.Context, id int32) (Perk, error) {
	row := q.db.QueryRow(ctx, getPerk, id)
	var i Perk
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.SpecializationID,
	)
	return i, err
}

const getPerks = `-- name: GetPerks :many
SELECT id, name, description, icon, specialization_id
FROM perks
`

func (q *Queries) GetPerks(ctx context.Context) ([]Perk, error) {
	rows, err := q.db.Query(ctx, getPerks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Perk
	for rows.Next() {
		var i Perk
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.SpecializationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerksByName = `-- name: GetPerksByName :many
SELECT id, name, description, icon, specialization_id
FROM perks
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetPerksByName(ctx context.Context, dollar_1 pgtype.Text) ([]Perk, error) {
	rows, err := q.db.Query(ctx, getPerksByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Perk
	for rows.Next() {
		var i Perk
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.SpecializationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRace = `-- name: GetRace :one
SELECT id, name, icon
FROM races
WHERE id = $1
`

func (q *Queries) GetRace(ctx context.Context, id int32) (Race, error) {
	row := q.db.QueryRow(ctx, getRace, id)
	var i Race
	err := row.Scan(&i.ID, &i.Name, &i.Icon)
	return i, err
}

const getRaces = `-- name: GetRaces :many
SELECT id, name, icon
FROM races
`

func (q *Queries) GetRaces(ctx context.Context) ([]Race, error) {
	rows, err := q.db.Query(ctx, getRaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Race
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByClassName = `-- name: GetRacesByClassName :many
SELECT r.id, r.name, r.icon
FROM races r
    JOIN creatures c ON r.id = c.race
    JOIN classes cl ON c.class_id = cl.id
WHERE cl.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByClassName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error) {
	rows, err := q.db.Query(ctx, getRacesByClassName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Race
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByCreatureName = `-- name: GetRacesByCreatureName :many
SELECT r.id, r.name, r.icon
FROM races r
    JOIN creatures c ON r.id = c.race_id
WHERE c.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByCreatureName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error) {
	rows, err := q.db.Query(ctx, getRacesByCreatureName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Race
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByName = `-- name: GetRacesByName :many
SELECT id, name, icon
FROM races
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error) {
	rows, err := q.db.Query(ctx, getRacesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Race
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByTraitName = `-- name: GetRacesByTraitName :many
SELECT r.id, r.name, r.icon
FROM races r
    JOIN creatures c ON r.id = c.race_id
    JOIN traits t ON c.trait_id = t.id
WHERE t.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByTraitName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error) {
	rows, err := q.db.Query(ctx, getRacesByTraitName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Race
	for rows.Next() {
		var i Race
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelic = `-- name: GetRelic :one
SELECT r.id,
    r.name,
    '/icons/relics/'|| r.id::text AS icon,
    r.bonuses,
    s.id as stat_id,
    s.type as stat_type
FROM relics r
    LEFT JOIN stats s ON r.stat_id = s.id
WHERE r.id = $1
`

type GetRelicRow struct {
	ID       int32        `json:"id"`
	Name     string       `json:"name"`
	Icon     interface{}  `json:"icon"`
	Bonuses  []string     `json:"bonuses"`
	StatID   pgtype.Int4  `json:"stat_id"`
	StatType NullStatType `json:"stat_type"`
}

func (q *Queries) GetRelic(ctx context.Context, id int32) (GetRelicRow, error) {
	row := q.db.QueryRow(ctx, getRelic, id)
	var i GetRelicRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Bonuses,
		&i.StatID,
		&i.StatType,
	)
	return i, err
}

const getRelicIconById = `-- name: GetRelicIconById :one
SELECT icon
FROM relics
WHERE id = $1
`

func (q *Queries) GetRelicIconById(ctx context.Context, id int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRelicIconById, id)
	var icon []byte
	err := row.Scan(&icon)
	return icon, err
}

const getRelics = `-- name: GetRelics :many
SELECT r.id,
    r.name,
    '/icons/relics/'|| r.id::text AS icon,
    r.bonuses,
    s.id as stat_id,
    s.type as stat_type
FROM relics r
    LEFT JOIN stats s ON r.stat_id = s.id
`

type GetRelicsRow struct {
	ID       int32        `json:"id"`
	Name     string       `json:"name"`
	Icon     interface{}  `json:"icon"`
	Bonuses  []string     `json:"bonuses"`
	StatID   pgtype.Int4  `json:"stat_id"`
	StatType NullStatType `json:"stat_type"`
}

func (q *Queries) GetRelics(ctx context.Context) ([]GetRelicsRow, error) {
	rows, err := q.db.Query(ctx, getRelics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelicsRow
	for rows.Next() {
		var i GetRelicsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Bonuses,
			&i.StatID,
			&i.StatType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelicsByName = `-- name: GetRelicsByName :many
SELECT r.id,
    r.name,
    '/icons/relics/'|| r.id::text AS icon,
    r.bonuses,
    s.id as stat_id,
    s.type as stat_type
FROM relics r
    LEFT JOIN stats s ON r.stat_id = s.id
WHERE r.name ILIKE '%' || $1 || '%'
`

type GetRelicsByNameRow struct {
	ID       int32        `json:"id"`
	Name     string       `json:"name"`
	Icon     interface{}  `json:"icon"`
	Bonuses  []string     `json:"bonuses"`
	StatID   pgtype.Int4  `json:"stat_id"`
	StatType NullStatType `json:"stat_type"`
}

func (q *Queries) GetRelicsByName(ctx context.Context, dollar_1 pgtype.Text) ([]GetRelicsByNameRow, error) {
	rows, err := q.db.Query(ctx, getRelicsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRelicsByNameRow
	for rows.Next() {
		var i GetRelicsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Bonuses,
			&i.StatID,
			&i.StatType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecialization = `-- name: GetSpecialization :one
SELECT id, name, description, icon
FROM specializations
WHERE id = $1
`

func (q *Queries) GetSpecialization(ctx context.Context, id int32) (Specialization, error) {
	row := q.db.QueryRow(ctx, getSpecialization, id)
	var i Specialization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
	)
	return i, err
}

const getSpecializations = `-- name: GetSpecializations :many
SELECT id, name, description, icon
FROM specializations
`

func (q *Queries) GetSpecializations(ctx context.Context) ([]Specialization, error) {
	rows, err := q.db.Query(ctx, getSpecializations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialization
	for rows.Next() {
		var i Specialization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecializationsByName = `-- name: GetSpecializationsByName :many
SELECT id, name, description, icon
FROM specializations
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetSpecializationsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Specialization, error) {
	rows, err := q.db.Query(ctx, getSpecializationsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialization
	for rows.Next() {
		var i Specialization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpell = `-- name: GetSpell :one
SELECT id, name, description, charges, class_id
FROM spells
WHERE id = $1
`

func (q *Queries) GetSpell(ctx context.Context, id int32) (Spell, error) {
	row := q.db.QueryRow(ctx, getSpell, id)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Charges,
		&i.ClassID,
	)
	return i, err
}

const getSpellProperties = `-- name: GetSpellProperties :many
SELECT id, name, material_id
FROM spell_properties
`

func (q *Queries) GetSpellProperties(ctx context.Context) ([]SpellProperty, error) {
	rows, err := q.db.Query(ctx, getSpellProperties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellProperty
	for rows.Next() {
		var i SpellProperty
		if err := rows.Scan(&i.ID, &i.Name, &i.MaterialID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellPropertiesByName = `-- name: GetSpellPropertiesByName :many
SELECT id, name, material_id
FROM spell_properties
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetSpellPropertiesByName(ctx context.Context, dollar_1 pgtype.Text) ([]SpellProperty, error) {
	rows, err := q.db.Query(ctx, getSpellPropertiesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellProperty
	for rows.Next() {
		var i SpellProperty
		if err := rows.Scan(&i.ID, &i.Name, &i.MaterialID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellProperty = `-- name: GetSpellProperty :one
SELECT id, name, material_id
FROM spell_properties
WHERE id = $1
`

func (q *Queries) GetSpellProperty(ctx context.Context, id int32) (SpellProperty, error) {
	row := q.db.QueryRow(ctx, getSpellProperty, id)
	var i SpellProperty
	err := row.Scan(&i.ID, &i.Name, &i.MaterialID)
	return i, err
}

const getSpells = `-- name: GetSpells :many
SELECT id, name, description, charges, class_id
FROM spells
`

func (q *Queries) GetSpells(ctx context.Context) ([]Spell, error) {
	rows, err := q.db.Query(ctx, getSpells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Spell
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Charges,
			&i.ClassID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsByName = `-- name: GetSpellsByName :many
SELECT id, name, description, charges, class_id
FROM spells
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetSpellsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Spell, error) {
	rows, err := q.db.Query(ctx, getSpellsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Spell
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Charges,
			&i.ClassID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStat = `-- name: GetStat :one
SELECT id, type, icon
FROM stats
WHERE id = $1
`

func (q *Queries) GetStat(ctx context.Context, id int32) (Stat, error) {
	row := q.db.QueryRow(ctx, getStat, id)
	var i Stat
	err := row.Scan(&i.ID, &i.Type, &i.Icon)
	return i, err
}

const getStatGrowthsByCreatureId = `-- name: GetStatGrowthsByCreatureId :many
SELECT csg.id,
    c.name as creature_name,
    s.type as stat_type,
    csg.growth_rate
FROM creature_stat_growth csg
    JOIN stats s ON csg.stat_id = s.id
    JOIN creatures c ON csg.creature_id = c.id
WHERE csg.creature_id = $1
`

type GetStatGrowthsByCreatureIdRow struct {
	ID           int32    `json:"id"`
	CreatureName string   `json:"creature_name"`
	StatType     StatType `json:"stat_type"`
	GrowthRate   int32    `json:"growth_rate"`
}

func (q *Queries) GetStatGrowthsByCreatureId(ctx context.Context, creatureID int32) ([]GetStatGrowthsByCreatureIdRow, error) {
	rows, err := q.db.Query(ctx, getStatGrowthsByCreatureId, creatureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatGrowthsByCreatureIdRow
	for rows.Next() {
		var i GetStatGrowthsByCreatureIdRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatureName,
			&i.StatType,
			&i.GrowthRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStats = `-- name: GetStats :many
SELECT id, type, icon
FROM stats
`

func (q *Queries) GetStats(ctx context.Context) ([]Stat, error) {
	rows, err := q.db.Query(ctx, getStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stat
	for rows.Next() {
		var i Stat
		if err := rows.Scan(&i.ID, &i.Type, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByType = `-- name: GetStatsByType :many
SELECT id, type, icon
FROM stats
WHERE type::text ILIKE '%' || $1 || '%'
`

func (q *Queries) GetStatsByType(ctx context.Context, dollar_1 pgtype.Text) ([]Stat, error) {
	rows, err := q.db.Query(ctx, getStatsByType, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stat
	for rows.Next() {
		var i Stat
		if err := rows.Scan(&i.ID, &i.Type, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsCount = `-- name: GetStatsCount :one
SELECT COUNT(*)
FROM stats
`

func (q *Queries) GetStatsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getStatsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTrait = `-- name: GetTrait :one
SELECT id, name, description, material_id
FROM traits
WHERE id = $1
`

func (q *Queries) GetTrait(ctx context.Context, id int32) (Trait, error) {
	row := q.db.QueryRow(ctx, getTrait, id)
	var i Trait
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MaterialID,
	)
	return i, err
}

const getTraits = `-- name: GetTraits :many
SELECT id, name, description, material_id
FROM traits
`

func (q *Queries) GetTraits(ctx context.Context) ([]Trait, error) {
	rows, err := q.db.Query(ctx, getTraits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trait
	for rows.Next() {
		var i Trait
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraitsByCreatureName = `-- name: GetTraitsByCreatureName :many
SELECT t.id, t.name, t.description, t.material_id
FROM traits t
    JOIN creatures c ON t.id = c.trait_id
WHERE c.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetTraitsByCreatureName(ctx context.Context, dollar_1 pgtype.Text) ([]Trait, error) {
	rows, err := q.db.Query(ctx, getTraitsByCreatureName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trait
	for rows.Next() {
		var i Trait
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraitsByName = `-- name: GetTraitsByName :many
SELECT id, name, description, material_id
FROM traits
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetTraitsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Trait, error) {
	rows, err := q.db.Query(ctx, getTraitsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trait
	for rows.Next() {
		var i Trait
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materialExists = `-- name: MaterialExists :one
SELECT EXISTS(
        SELECT 1
        FROM materials
        WHERE id = $1
    ) as exists
`

func (q *Queries) MaterialExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, materialExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const traitExists = `-- name: TraitExists :one
SELECT EXISTS(
        SELECT 1
        FROM traits
        WHERE id = $1
    ) as exists
`

func (q *Queries) TraitExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, traitExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
