// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (int32, error)
	CreateClass(ctx context.Context, arg CreateClassParams) (int32, error)
	CreateCreature(ctx context.Context, arg CreateCreatureParams) (int32, error)
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (int32, error)
	CreatePerk(ctx context.Context, arg CreatePerkParams) (int32, error)
	CreateRace(ctx context.Context, arg CreateRaceParams) (int32, error)
	CreateSpecialization(ctx context.Context, arg CreateSpecializationParams) (int32, error)
	CreateSpell(ctx context.Context, arg CreateSpellParams) (int32, error)
	CreateSpellProperty(ctx context.Context, arg CreateSpellPropertyParams) (int32, error)
	CreateStat(ctx context.Context, type_ StatType) (int32, error)
	CreateTrait(ctx context.Context, arg CreateTraitParams) (int32, error)
	DeleteArtifact(ctx context.Context, id int32) error
	DeleteClass(ctx context.Context, id int32) error
	DeleteCreature(ctx context.Context, id int32) error
	DeleteMaterial(ctx context.Context, id int32) error
	DeletePerk(ctx context.Context, id int32) error
	DeleteRace(ctx context.Context, id int32) error
	DeleteSpecialization(ctx context.Context, id int32) error
	DeleteSpell(ctx context.Context, id int32) error
	DeleteSpellProperty(ctx context.Context, id int32) error
	DeleteStat(ctx context.Context, id int32) error
	DeleteTrait(ctx context.Context, id int32) error
	GetArtifact(ctx context.Context, id int32) (Artifact, error)
	GetArtifacts(ctx context.Context) ([]Artifact, error)
	GetArtifactsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Artifact, error)
	GetClass(ctx context.Context, id int32) (Class, error)
	GetClasses(ctx context.Context) ([]Class, error)
	GetClassesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Class, error)
	GetCreature(ctx context.Context, id int32) (Creature, error)
	GetCreatures(ctx context.Context) ([]Creature, error)
	GetCreaturesByClassName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error)
	GetCreaturesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error)
	GetCreaturesByRaceName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error)
	GetCreaturesByTraitName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error)
	GetMaterial(ctx context.Context, id int32) (Material, error)
	GetMaterials(ctx context.Context) ([]Material, error)
	GetMaterialsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Material, error)
	GetPerk(ctx context.Context, id int32) (Perk, error)
	GetPerks(ctx context.Context) ([]Perk, error)
	GetPerksByName(ctx context.Context, dollar_1 pgtype.Text) ([]Perk, error)
	GetRace(ctx context.Context, id int32) (Race, error)
	GetRaces(ctx context.Context) ([]Race, error)
	GetRacesByClassName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error)
	GetRacesByCreatureName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error)
	GetRacesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error)
	GetRacesByTraitName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error)
	GetSpecialization(ctx context.Context, id int32) (Specialization, error)
	GetSpecializations(ctx context.Context) ([]Specialization, error)
	GetSpecializationsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Specialization, error)
	GetSpell(ctx context.Context, id int32) (Spell, error)
	GetSpellProperties(ctx context.Context) ([]SpellProperty, error)
	GetSpellPropertiesByName(ctx context.Context, dollar_1 pgtype.Text) ([]SpellProperty, error)
	GetSpellProperty(ctx context.Context, id int32) (SpellProperty, error)
	GetSpells(ctx context.Context) ([]Spell, error)
	GetSpellsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Spell, error)
	GetStat(ctx context.Context, id int32) (Stat, error)
	GetStats(ctx context.Context) ([]Stat, error)
	GetStatsByType(ctx context.Context, dollar_1 pgtype.Text) ([]Stat, error)
	GetTrait(ctx context.Context, id int32) (Trait, error)
	GetTraits(ctx context.Context) ([]Trait, error)
	GetTraitsByCreatureName(ctx context.Context, dollar_1 pgtype.Text) ([]Trait, error)
	GetTraitsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Trait, error)
}

var _ Querier = (*Queries)(nil)
