// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchInsertArtifactsParams struct {
	ID     int32  `json:"id"`
	Name   string `json:"name"`
	Icon   []byte `json:"icon"`
	StatID int32  `json:"stat_id"`
}

type BatchInsertClassesParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Icon []byte `json:"icon"`
}

type BatchInsertCreatureStatGrowthParams struct {
	ID         int32 `json:"id"`
	CreatureID int32 `json:"creature_id"`
	StatID     int32 `json:"stat_id"`
	GrowthRate int32 `json:"growth_rate"`
}

type BatchInsertCreaturesParams struct {
	ID      int32       `json:"id"`
	Name    string      `json:"name"`
	Icon    []byte      `json:"icon"`
	TraitID pgtype.Int4 `json:"trait_id"`
	ClassID int32       `json:"class_id"`
	RaceID  int32       `json:"race_id"`
}

type BatchInsertMaterialStatsParams struct {
	ID         int32       `json:"id"`
	MaterialID int32       `json:"material_id"`
	StatID     int32       `json:"stat_id"`
	StatId2    pgtype.Int4 `json:"stat_id2"`
}

type BatchInsertMaterialsParams struct {
	ID   int32        `json:"id"`
	Name string       `json:"name"`
	Icon []byte       `json:"icon"`
	Type MaterialType `json:"type"`
}

type BatchInsertPerksParams struct {
	ID               int32  `json:"id"`
	Name             string `json:"name"`
	Description      string `json:"description"`
	Icon             []byte `json:"icon"`
	SpecializationID int32  `json:"specialization_id"`
}

type BatchInsertRacesParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Icon []byte `json:"icon"`
}

type BatchInsertRelicsParams struct {
	ID      int32    `json:"id"`
	Name    string   `json:"name"`
	Icon    []byte   `json:"icon"`
	Bonuses []string `json:"bonuses"`
	StatID  int32    `json:"stat_id"`
}

type BatchInsertSpecializationsParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Icon        []byte `json:"icon"`
}

type BatchInsertSpellPropertiesParams struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	MaterialID int32  `json:"material_id"`
}

type BatchInsertSpellsParams struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Charges     int32  `json:"charges"`
	ClassID     int32  `json:"class_id"`
}

type BatchInsertStatsParams struct {
	ID   int32    `json:"id"`
	Type StatType `json:"type"`
	Icon []byte   `json:"icon"`
}

type BatchInsertTraitsParams struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	MaterialID  pgtype.Int4 `json:"material_id"`
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, name, icon, stat_id
FROM artifacts
WHERE id = $1
`

func (q *Queries) GetArtifact(ctx context.Context, id int32) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.StatID,
	)
	return i, err
}

const getArtifacts = `-- name: GetArtifacts :many
SELECT id, name, icon, stat_id
FROM artifacts
`

func (q *Queries) GetArtifacts(ctx context.Context) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, getArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.StatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtifactsByName = `-- name: GetArtifactsByName :many
SELECT id, name, icon, stat_id
FROM artifacts
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetArtifactsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, getArtifactsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.StatID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClass = `-- name: GetClass :one
SELECT id, name, icon
FROM classes
WHERE id = $1
`

func (q *Queries) GetClass(ctx context.Context, id int32) (Class, error) {
	row := q.db.QueryRow(ctx, getClass, id)
	var i Class
	err := row.Scan(&i.ID, &i.Name, &i.Icon)
	return i, err
}

const getClasses = `-- name: GetClasses :many
SELECT id, name, icon
FROM classes
`

func (q *Queries) GetClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.Query(ctx, getClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassesByName = `-- name: GetClassesByName :many
SELECT id, name, icon
FROM classes
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetClassesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Class, error) {
	rows, err := q.db.Query(ctx, getClassesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreature = `-- name: GetCreature :one
SELECT id, name, icon, trait, trait_description, class, race, stats
FROM creatures_view
WHERE id = $1
`

func (q *Queries) GetCreature(ctx context.Context, id int32) (CreaturesView, error) {
	row := q.db.QueryRow(ctx, getCreature, id)
	var i CreaturesView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Trait,
		&i.TraitDescription,
		&i.Class,
		&i.Race,
		&i.Stats,
	)
	return i, err
}

const getCreatureIconById = `-- name: GetCreatureIconById :one
SELECT icon
FROM creatures
WHERE id = $1
`

func (q *Queries) GetCreatureIconById(ctx context.Context, id int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCreatureIconById, id)
	var icon []byte
	err := row.Scan(&icon)
	return icon, err
}

const getCreatures = `-- name: GetCreatures :many
SELECT id, name, icon, trait, trait_description, class, race, stats
FROM creatures_view
`

func (q *Queries) GetCreatures(ctx context.Context) ([]CreaturesView, error) {
	rows, err := q.db.Query(ctx, getCreatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreaturesView
	for rows.Next() {
		var i CreaturesView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Trait,
			&i.TraitDescription,
			&i.Class,
			&i.Race,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByClassName = `-- name: GetCreaturesByClassName :many
SELECT id, name, icon, trait, trait_description, class, race, stats
FROM creatures_view
WHERE class ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByClassName(ctx context.Context, dollar_1 pgtype.Text) ([]CreaturesView, error) {
	rows, err := q.db.Query(ctx, getCreaturesByClassName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreaturesView
	for rows.Next() {
		var i CreaturesView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Trait,
			&i.TraitDescription,
			&i.Class,
			&i.Race,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByName = `-- name: GetCreaturesByName :many
SELECT id, name, icon, trait, trait_description, class, race, stats
FROM creatures_view
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByName(ctx context.Context, dollar_1 pgtype.Text) ([]CreaturesView, error) {
	rows, err := q.db.Query(ctx, getCreaturesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreaturesView
	for rows.Next() {
		var i CreaturesView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Trait,
			&i.TraitDescription,
			&i.Class,
			&i.Race,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByRaceName = `-- name: GetCreaturesByRaceName :many
SELECT id, name, icon, trait, trait_description, class, race, stats
FROM creatures_view
WHERE race ILIKE '%' || $1 || $1 || '%'
`

func (q *Queries) GetCreaturesByRaceName(ctx context.Context, dollar_1 pgtype.Text) ([]CreaturesView, error) {
	rows, err := q.db.Query(ctx, getCreaturesByRaceName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreaturesView
	for rows.Next() {
		var i CreaturesView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Trait,
			&i.TraitDescription,
			&i.Class,
			&i.Race,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCreaturesByTraitName = `-- name: GetCreaturesByTraitName :many
SELECT id, name, icon, trait, trait_description, class, race, stats
FROM creatures_view
WHERE trait ILIKE '%' || $1 || '%'
`

func (q *Queries) GetCreaturesByTraitName(ctx context.Context, dollar_1 pgtype.Text) ([]CreaturesView, error) {
	rows, err := q.db.Query(ctx, getCreaturesByTraitName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreaturesView
	for rows.Next() {
		var i CreaturesView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Trait,
			&i.TraitDescription,
			&i.Class,
			&i.Race,
			&i.Stats,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterial = `-- name: GetMaterial :one
SELECT id, name, icon, type, stat_id1, stat_id2
FROM materials_view
WHERE id = $1
`

func (q *Queries) GetMaterial(ctx context.Context, id int32) (MaterialsView, error) {
	row := q.db.QueryRow(ctx, getMaterial, id)
	var i MaterialsView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Type,
		&i.StatId1,
		&i.StatId2,
	)
	return i, err
}

const getMaterialIconById = `-- name: GetMaterialIconById :one
SELECT icon
FROM materials
WHERE id = $1
`

func (q *Queries) GetMaterialIconById(ctx context.Context, id int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, getMaterialIconById, id)
	var icon []byte
	err := row.Scan(&icon)
	return icon, err
}

const getMaterials = `-- name: GetMaterials :many
SELECT id, name, icon, type, stat_id1, stat_id2
FROM materials_view
`

func (q *Queries) GetMaterials(ctx context.Context) ([]MaterialsView, error) {
	rows, err := q.db.Query(ctx, getMaterials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaterialsView
	for rows.Next() {
		var i MaterialsView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Type,
			&i.StatId1,
			&i.StatId2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaterialsByName = `-- name: GetMaterialsByName :many
SELECT id, name, icon, type, stat_id1, stat_id2
FROM materials_view
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetMaterialsByName(ctx context.Context, dollar_1 pgtype.Text) ([]MaterialsView, error) {
	rows, err := q.db.Query(ctx, getMaterialsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaterialsView
	for rows.Next() {
		var i MaterialsView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Type,
			&i.StatId1,
			&i.StatId2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerk = `-- name: GetPerk :one
SELECT id, name, description, icon, specialization_id
FROM perks
WHERE id = $1
`

func (q *Queries) GetPerk(ctx context.Context, id int32) (Perk, error) {
	row := q.db.QueryRow(ctx, getPerk, id)
	var i Perk
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.SpecializationID,
	)
	return i, err
}

const getPerks = `-- name: GetPerks :many
SELECT id, name, description, icon, specialization_id
FROM perks
`

func (q *Queries) GetPerks(ctx context.Context) ([]Perk, error) {
	rows, err := q.db.Query(ctx, getPerks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Perk
	for rows.Next() {
		var i Perk
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.SpecializationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerksByName = `-- name: GetPerksByName :many
SELECT id, name, description, icon, specialization_id
FROM perks
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetPerksByName(ctx context.Context, dollar_1 pgtype.Text) ([]Perk, error) {
	rows, err := q.db.Query(ctx, getPerksByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Perk
	for rows.Next() {
		var i Perk
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.SpecializationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRace = `-- name: GetRace :one
SELECT id, name, icon
FROM races_view
WHERE id = $1
`

func (q *Queries) GetRace(ctx context.Context, id int32) (RacesView, error) {
	row := q.db.QueryRow(ctx, getRace, id)
	var i RacesView
	err := row.Scan(&i.ID, &i.Name, &i.Icon)
	return i, err
}

const getRaces = `-- name: GetRaces :many
SELECT id, name, icon
FROM races_view
`

func (q *Queries) GetRaces(ctx context.Context) ([]RacesView, error) {
	rows, err := q.db.Query(ctx, getRaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacesView
	for rows.Next() {
		var i RacesView
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByClassName = `-- name: GetRacesByClassName :many
SELECT r.id, r.name, r.icon
FROM races_view r
    JOIN creatures c ON r.id = c.race
    JOIN classes cl ON c.class_id = cl.id
WHERE cl.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByClassName(ctx context.Context, dollar_1 pgtype.Text) ([]RacesView, error) {
	rows, err := q.db.Query(ctx, getRacesByClassName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacesView
	for rows.Next() {
		var i RacesView
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByCreatureName = `-- name: GetRacesByCreatureName :many
SELECT r.id, r.name, r.icon
FROM races_view r
    JOIN creatures c ON r.id = c.race_id
WHERE c.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByCreatureName(ctx context.Context, dollar_1 pgtype.Text) ([]RacesView, error) {
	rows, err := q.db.Query(ctx, getRacesByCreatureName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacesView
	for rows.Next() {
		var i RacesView
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByName = `-- name: GetRacesByName :many
SELECT id, name, icon
FROM races_view
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByName(ctx context.Context, dollar_1 pgtype.Text) ([]RacesView, error) {
	rows, err := q.db.Query(ctx, getRacesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacesView
	for rows.Next() {
		var i RacesView
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRacesByTraitName = `-- name: GetRacesByTraitName :many
SELECT r.id, r.name, r.icon
FROM races_view r
    JOIN creatures c ON r.id = c.race_id
    JOIN traits t ON c.trait_id = t.id
WHERE t.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRacesByTraitName(ctx context.Context, dollar_1 pgtype.Text) ([]RacesView, error) {
	rows, err := q.db.Query(ctx, getRacesByTraitName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RacesView
	for rows.Next() {
		var i RacesView
		if err := rows.Scan(&i.ID, &i.Name, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelic = `-- name: GetRelic :one
SELECT id, name, icon, bonuses, stat_id, stat_type
FROM relics_view
WHERE id = $1
`

func (q *Queries) GetRelic(ctx context.Context, id int32) (RelicsView, error) {
	row := q.db.QueryRow(ctx, getRelic, id)
	var i RelicsView
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Bonuses,
		&i.StatID,
		&i.StatType,
	)
	return i, err
}

const getRelicIconById = `-- name: GetRelicIconById :one
SELECT icon
FROM relics
WHERE id = $1
`

func (q *Queries) GetRelicIconById(ctx context.Context, id int32) ([]byte, error) {
	row := q.db.QueryRow(ctx, getRelicIconById, id)
	var icon []byte
	err := row.Scan(&icon)
	return icon, err
}

const getRelics = `-- name: GetRelics :many
SELECT id, name, icon, bonuses, stat_id, stat_type
FROM relics_view
`

func (q *Queries) GetRelics(ctx context.Context) ([]RelicsView, error) {
	rows, err := q.db.Query(ctx, getRelics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelicsView
	for rows.Next() {
		var i RelicsView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Bonuses,
			&i.StatID,
			&i.StatType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelicsByName = `-- name: GetRelicsByName :many
SELECT id, name, icon, bonuses, stat_id, stat_type
FROM relics_view
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetRelicsByName(ctx context.Context, dollar_1 pgtype.Text) ([]RelicsView, error) {
	rows, err := q.db.Query(ctx, getRelicsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RelicsView
	for rows.Next() {
		var i RelicsView
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Bonuses,
			&i.StatID,
			&i.StatType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecialization = `-- name: GetSpecialization :one
SELECT id, name, description, icon
FROM specializations
WHERE id = $1
`

func (q *Queries) GetSpecialization(ctx context.Context, id int32) (Specialization, error) {
	row := q.db.QueryRow(ctx, getSpecialization, id)
	var i Specialization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
	)
	return i, err
}

const getSpecializations = `-- name: GetSpecializations :many
SELECT id, name, description, icon
FROM specializations
`

func (q *Queries) GetSpecializations(ctx context.Context) ([]Specialization, error) {
	rows, err := q.db.Query(ctx, getSpecializations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialization
	for rows.Next() {
		var i Specialization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpecializationsByName = `-- name: GetSpecializationsByName :many
SELECT id, name, description, icon
FROM specializations
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetSpecializationsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Specialization, error) {
	rows, err := q.db.Query(ctx, getSpecializationsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialization
	for rows.Next() {
		var i Specialization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpell = `-- name: GetSpell :one
SELECT id, name, description, charges, class_id
FROM spells
WHERE id = $1
`

func (q *Queries) GetSpell(ctx context.Context, id int32) (Spell, error) {
	row := q.db.QueryRow(ctx, getSpell, id)
	var i Spell
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Charges,
		&i.ClassID,
	)
	return i, err
}

const getSpellProperties = `-- name: GetSpellProperties :many
SELECT id, name, material_id
FROM spell_properties
`

func (q *Queries) GetSpellProperties(ctx context.Context) ([]SpellProperty, error) {
	rows, err := q.db.Query(ctx, getSpellProperties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellProperty
	for rows.Next() {
		var i SpellProperty
		if err := rows.Scan(&i.ID, &i.Name, &i.MaterialID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellPropertiesByName = `-- name: GetSpellPropertiesByName :many
SELECT id, name, material_id
FROM spell_properties
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetSpellPropertiesByName(ctx context.Context, dollar_1 pgtype.Text) ([]SpellProperty, error) {
	rows, err := q.db.Query(ctx, getSpellPropertiesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellProperty
	for rows.Next() {
		var i SpellProperty
		if err := rows.Scan(&i.ID, &i.Name, &i.MaterialID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellProperty = `-- name: GetSpellProperty :one
SELECT id, name, material_id
FROM spell_properties
WHERE id = $1
`

func (q *Queries) GetSpellProperty(ctx context.Context, id int32) (SpellProperty, error) {
	row := q.db.QueryRow(ctx, getSpellProperty, id)
	var i SpellProperty
	err := row.Scan(&i.ID, &i.Name, &i.MaterialID)
	return i, err
}

const getSpells = `-- name: GetSpells :many
SELECT id, name, description, charges, class_id
FROM spells
`

func (q *Queries) GetSpells(ctx context.Context) ([]Spell, error) {
	rows, err := q.db.Query(ctx, getSpells)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Spell
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Charges,
			&i.ClassID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsByName = `-- name: GetSpellsByName :many
SELECT id, name, description, charges, class_id
FROM spells
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetSpellsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Spell, error) {
	rows, err := q.db.Query(ctx, getSpellsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Spell
	for rows.Next() {
		var i Spell
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Charges,
			&i.ClassID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStat = `-- name: GetStat :one
SELECT id, type, icon
FROM stats
WHERE id = $1
`

func (q *Queries) GetStat(ctx context.Context, id int32) (Stat, error) {
	row := q.db.QueryRow(ctx, getStat, id)
	var i Stat
	err := row.Scan(&i.ID, &i.Type, &i.Icon)
	return i, err
}

const getStats = `-- name: GetStats :many
SELECT id, type, icon
FROM stats
`

func (q *Queries) GetStats(ctx context.Context) ([]Stat, error) {
	rows, err := q.db.Query(ctx, getStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stat
	for rows.Next() {
		var i Stat
		if err := rows.Scan(&i.ID, &i.Type, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsByType = `-- name: GetStatsByType :many
SELECT id, type, icon
FROM stats
WHERE type::text ILIKE '%' || $1 || '%'
`

func (q *Queries) GetStatsByType(ctx context.Context, dollar_1 pgtype.Text) ([]Stat, error) {
	rows, err := q.db.Query(ctx, getStatsByType, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Stat
	for rows.Next() {
		var i Stat
		if err := rows.Scan(&i.ID, &i.Type, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsCount = `-- name: GetStatsCount :one
SELECT COUNT(*)
FROM stats
`

func (q *Queries) GetStatsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getStatsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTrait = `-- name: GetTrait :one
SELECT id, name, description, material_id
FROM traits
WHERE id = $1
`

func (q *Queries) GetTrait(ctx context.Context, id int32) (Trait, error) {
	row := q.db.QueryRow(ctx, getTrait, id)
	var i Trait
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.MaterialID,
	)
	return i, err
}

const getTraits = `-- name: GetTraits :many
SELECT id, name, description, material_id
FROM traits
`

func (q *Queries) GetTraits(ctx context.Context) ([]Trait, error) {
	rows, err := q.db.Query(ctx, getTraits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trait
	for rows.Next() {
		var i Trait
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraitsByCreatureName = `-- name: GetTraitsByCreatureName :many
SELECT t.id, t.name, t.description, t.material_id
FROM traits t
    JOIN creatures c ON t.id = c.trait_id
WHERE c.name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetTraitsByCreatureName(ctx context.Context, dollar_1 pgtype.Text) ([]Trait, error) {
	rows, err := q.db.Query(ctx, getTraitsByCreatureName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trait
	for rows.Next() {
		var i Trait
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTraitsByName = `-- name: GetTraitsByName :many
SELECT id, name, description, material_id
FROM traits
WHERE name ILIKE '%' || $1 || '%'
`

func (q *Queries) GetTraitsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Trait, error) {
	rows, err := q.db.Query(ctx, getTraitsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trait
	for rows.Next() {
		var i Trait
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MaterialID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const materialExists = `-- name: MaterialExists :one
SELECT EXISTS(
        SELECT 1
        FROM materials
        WHERE id = $1
    ) as exists
`

func (q *Queries) MaterialExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, materialExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const traitExists = `-- name: TraitExists :one
SELECT EXISTS(
        SELECT 1
        FROM traits
        WHERE id = $1
    ) as exists
`

func (q *Queries) TraitExists(ctx context.Context, id int32) (bool, error) {
	row := q.db.QueryRow(ctx, traitExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
