// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BatchInsertArtifacts(ctx context.Context, arg []BatchInsertArtifactsParams) (int64, error)
	// Batch insert queries using COPY protocol for efficient seeding
	BatchInsertClasses(ctx context.Context, arg []BatchInsertClassesParams) (int64, error)
	BatchInsertCreatures(ctx context.Context, arg []BatchInsertCreaturesParams) (int64, error)
	BatchInsertMaterialStats(ctx context.Context, arg []BatchInsertMaterialStatsParams) (int64, error)
	BatchInsertMaterials(ctx context.Context, arg []BatchInsertMaterialsParams) (int64, error)
	BatchInsertPerks(ctx context.Context, arg []BatchInsertPerksParams) (int64, error)
	BatchInsertRaces(ctx context.Context, arg []BatchInsertRacesParams) (int64, error)
	BatchInsertRelics(ctx context.Context, arg []BatchInsertRelicsParams) (int64, error)
	BatchInsertSpecializations(ctx context.Context, arg []BatchInsertSpecializationsParams) (int64, error)
	BatchInsertSpellProperties(ctx context.Context, arg []BatchInsertSpellPropertiesParams) (int64, error)
	BatchInsertSpells(ctx context.Context, arg []BatchInsertSpellsParams) (int64, error)
	BatchInsertStats(ctx context.Context, arg []BatchInsertStatsParams) (int64, error)
	BatchInsertTraits(ctx context.Context, arg []BatchInsertTraitsParams) (int64, error)
	CreateArtifact(ctx context.Context, arg CreateArtifactParams) (int32, error)
	CreateClass(ctx context.Context, arg CreateClassParams) (int32, error)
	CreateCreature(ctx context.Context, arg CreateCreatureParams) (int32, error)
	CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error)
	CreateMaterialStat(ctx context.Context, arg CreateMaterialStatParams) (int32, error)
	CreatePerk(ctx context.Context, arg CreatePerkParams) (int32, error)
	CreateRace(ctx context.Context, arg CreateRaceParams) (int32, error)
	CreateRelic(ctx context.Context, arg CreateRelicParams) (int32, error)
	CreateSpecialization(ctx context.Context, arg CreateSpecializationParams) (int32, error)
	CreateSpell(ctx context.Context, arg CreateSpellParams) (int32, error)
	CreateSpellProperty(ctx context.Context, arg CreateSpellPropertyParams) (int32, error)
	CreateStat(ctx context.Context, arg CreateStatParams) (int32, error)
	CreateTrait(ctx context.Context, arg CreateTraitParams) (int32, error)
	DeleteArtifact(ctx context.Context, id int32) error
	DeleteClass(ctx context.Context, id int32) error
	DeleteCreature(ctx context.Context, id int32) error
	DeleteMaterial(ctx context.Context, id int32) error
	DeleteMaterialStat(ctx context.Context, id int32) error
	DeletePerk(ctx context.Context, id int32) error
	DeleteRace(ctx context.Context, id int32) error
	DeleteRelic(ctx context.Context, id int32) error
	DeleteSpecialization(ctx context.Context, id int32) error
	DeleteSpell(ctx context.Context, id int32) error
	DeleteSpellProperty(ctx context.Context, id int32) error
	DeleteStat(ctx context.Context, id int32) error
	DeleteTrait(ctx context.Context, id int32) error
	GetArtifact(ctx context.Context, id int32) (Artifact, error)
	GetArtifacts(ctx context.Context) ([]Artifact, error)
	GetArtifactsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Artifact, error)
	GetClass(ctx context.Context, id int32) (Class, error)
	GetClasses(ctx context.Context) ([]Class, error)
	GetClassesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Class, error)
	GetCreature(ctx context.Context, id int32) (Creature, error)
	GetCreatures(ctx context.Context) ([]Creature, error)
	GetCreaturesByClassName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error)
	GetCreaturesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error)
	GetCreaturesByRaceName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error)
	GetCreaturesByTraitName(ctx context.Context, dollar_1 pgtype.Text) ([]Creature, error)
	GetMaterial(ctx context.Context, id int32) (GetMaterialRow, error)
	GetMaterialStats(ctx context.Context, materialID int32) ([]GetMaterialStatsRow, error)
	GetMaterials(ctx context.Context) ([]GetMaterialsRow, error)
	GetMaterialsByName(ctx context.Context, dollar_1 pgtype.Text) ([]GetMaterialsByNameRow, error)
	GetPerk(ctx context.Context, id int32) (Perk, error)
	GetPerks(ctx context.Context) ([]Perk, error)
	GetPerksByName(ctx context.Context, dollar_1 pgtype.Text) ([]Perk, error)
	GetRace(ctx context.Context, id int32) (Race, error)
	GetRaces(ctx context.Context) ([]Race, error)
	GetRacesByClassName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error)
	GetRacesByCreatureName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error)
	GetRacesByName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error)
	GetRacesByTraitName(ctx context.Context, dollar_1 pgtype.Text) ([]Race, error)
	GetRelic(ctx context.Context, id int32) (GetRelicRow, error)
	GetRelics(ctx context.Context) ([]GetRelicsRow, error)
	GetRelicsByName(ctx context.Context, dollar_1 pgtype.Text) ([]GetRelicsByNameRow, error)
	GetSpecialization(ctx context.Context, id int32) (Specialization, error)
	GetSpecializations(ctx context.Context) ([]Specialization, error)
	GetSpecializationsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Specialization, error)
	GetSpell(ctx context.Context, id int32) (Spell, error)
	GetSpellProperties(ctx context.Context) ([]SpellProperty, error)
	GetSpellPropertiesByName(ctx context.Context, dollar_1 pgtype.Text) ([]SpellProperty, error)
	GetSpellProperty(ctx context.Context, id int32) (SpellProperty, error)
	GetSpells(ctx context.Context) ([]Spell, error)
	GetSpellsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Spell, error)
	GetStat(ctx context.Context, id int32) (Stat, error)
	GetStats(ctx context.Context) ([]Stat, error)
	GetStatsByType(ctx context.Context, dollar_1 pgtype.Text) ([]Stat, error)
	GetStatsCount(ctx context.Context) (int64, error)
	GetTrait(ctx context.Context, id int32) (Trait, error)
	GetTraits(ctx context.Context) ([]Trait, error)
	GetTraitsByCreatureName(ctx context.Context, dollar_1 pgtype.Text) ([]Trait, error)
	GetTraitsByName(ctx context.Context, dollar_1 pgtype.Text) ([]Trait, error)
	MaterialExists(ctx context.Context, id int32) (bool, error)
	TraitExists(ctx context.Context, id int32) (bool, error)
	UpdateMaterialStat(ctx context.Context, arg UpdateMaterialStatParams) error
}

var _ Querier = (*Queries)(nil)
